[
	{
		"id":"M_System",
		"desc":null,
		"tabs":[
			{"id":"M_Dashboard","desc":null,"read":"true","write":"true","execute":"true","url":"wsmbfile/[lang]/summary.html"},
			{"id":"M_ClientInfor","desc":null,"read":"true","write":"true","execute":"true","url":"wsmbfile/[lang]/terminalinfo.html"},
			{"id":"M_RateAnalyse","desc":null,"read":"true","write":"true","execute":"true","url":"wsmbfile/[lang]/flow_analysis.html"},
			{"id":"M_DeviceInfor","desc":null,"read":"true","write":"true","execute":"true","url":"wsmbfile/[lang]/device_info.html"},
			{"id":"M_NetworkInfor","desc":null,"read":"true","write":"true","execute":"true","url":"wsmbfile/[lang]/net_info.html"}
		]
	},
	{
		"id":"M_QuickNav",
		"desc":null,
		"tabs":[
			{"id":"I_QuickNav","desc":null,"read":"true","write":"true","execute":"true","url":"wsmbfile/[lang]/quick_config.html"}
		]
	},
	{
		"id":"M_NetworkCfg",
		"desc":null,
		"tabs":[
			{"id":"I_NetworkCfg","desc":null,"read":"true","write":"true","execute":"true","url":"wsmbfile/[lang]/networkcfg.html"}
		]
	},
	{
		"id":"M_WirelessCfg",
		"desc":null,
		"tabs":[
			{"id":"I_WirelessCfg","desc":null,"read":"true","write":"true","execute":"true","url":"wsmbfile/[lang]/wireless_setting.html"}
		]
	},
	{
		"id":"M_UserManager",
		"desc":null,
		"tabs":[
			{"id":"I_UserManager","desc":null,"read":"true","write":"true","execute":"true","url":"wsmbfile/[lang]/user_manager.html"}
		]
	},
	{
		"id":"M_SecurityPolicy",
		"desc":null,
		"tabs":[
			{"id":"I_SecurityPolicy","desc":null,"read":"true","write":"true","execute":"true","url":"wsmbfile/[lang]/securitypolicy.html"}
		]
	},
	{
		"id":"M_AppManager",
		"desc":null,
		"tabs":[
			{"id":"I_AppManager","desc":null,"read":"true","write":"true","execute":"true","url":"wsmbfile/[lang]/app_manager.html"}
		]
	},
	{
		"id":"M_SystemCfg",
		"desc":null,
		"tabs":[
			{"id":"I_SystemCfg","desc":null,"read":"true","write":"true","execute":"true","url":"wsmbfile/[lang]/systemsetting.html"}
		]
	}
]